#!/usr/bin/env bash

MAP_FILE='map.txt'
MAP_SIZE='map_size.tin'
REFRESH_RATE=.25

while [ "true"  ]; do
    COLS=$(expr $(expr $(tput cols) - 1) '/' 3 '*' 3 + 1)
    ROWS=$(expr $(expr $(tput lines) - 1) '/' 3 '*' 3 + 1)
    echo \#VAR MAP_ROWS $COLS\; > $MAP_SIZE
    echo \#VAR MAP_LINES $ROWS\; >> $MAP_SIZE
    clear
    cat $MAP_FILE
    sleep $REFRESH_RATE
done
